name: smart_reminders
description: Smart Reminders Everywhere...

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  provider: ^6.0.2
  sqflite: ^2.0.2
  # intl: ^0.17.0
  # intl: 0.17.0-nullsafety.2

  flutter_svg: ^1.0.2
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  # intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/yearly_filled.svg
    - assets/icons/yearly_outlined.svg
    - assets/icons/monthly_filled.svg
    - assets/icons/monthly_outlined.svg
    - assets/icons/weekly_filled.svg
    - assets/icons/weekly_outlined.svg
    - assets/icons/daily_filled.svg
    - assets/icons/daily_outlined.svg

  fonts:
    - family: Gotham Book
      fonts:
        - asset: assets/fonts/Gotham-Book.ttf

    - family: Gotham Bold
      fonts:
        - asset: assets/fonts/Gotham-Bold.ttf
        
    - family: Gotham Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.ttf
  
flutter_intl:
  enabled: true